package: thumb
version: '1.0-alpha1'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/thumb


requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    media_manager: ">1.0.0"
    yrewrite: ">2.0.0"

page:
    title: translate:thumb_title
    icon: rex-icon fa-gear

pages:
    settings:
        title: translate:thumb_config
        icon: rex-icon fa-gear
        perm: thumb
    docs:
        title: translate:thumb_docs
        subPath: README.md
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: thumb[docs]

default_config:
    api: 'hcti'
    hcti_username: ''
    hcti_api_key: ''
    h2in_api_key: ''
    media_manager_profile: 'yrewrite_seo_image'
    background_image: 'thumb_bg.png'
