package: thumb
version: '0.0.1-dev'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/thumb


requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13

page:
    title: translate:thumb_title
    icon: rex-icon fa-gear

pages:
    settings:
        title: translate:thumb_settings
        icon: rex-icon fa-gear
        perm: thumb
    docs:
        title: translate:thumb_docs
        subPath: README.md
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: thumb[docs]

default_config:
    hcti_api_key: ''
