package: thumb
version: '0.0.4'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/thumb


requires:
    php:
        version: '>8.1,<9'
    redaxo: ^5.17
    media_manager: ">1.0.0"
    yrewrite: ">2.0.0"

pages:
    media_manager/thumb:
        title: translate:thumb_title
        icon: rex-icon fa-file-image
        subpages:
            settings:
                title: translate:thumb_config
                icon: rex-icon fa-cog
            docs:
                title: translate:thumb_docs
                subPath: README.md
                icon: rex-icon fa-info-circle
                itemclass: pull-right

default_config:
    api: 'hcti'
    hcti_username: ''
    hcti_api_key: ''
    h2in_api_key: ''
    media_manager_profile: 'thumb'
    background_image: 'thumb_bg.png'
