package: thumb
version: '1.0.0-dev-2024-09-06'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/thumb


requires:
    php:
        version: '^8.1'
    redaxo: ^5.17.0
    packages:
        media_manager: "^2.1.0"
        yrewrite: "^2.10.0"

pages:
    yrewrite/thumb:
        title: translate:thumb_title
        icon: rex-icon fa-file-image
        subpages:
            settings:
                title: translate:thumb_config
                icon: rex-icon fa-cog
            history:
                title: translate:thumb_history
                icon: rex-icon fa-history
            docs:
                title: translate:thumb_docs
                subPath: README.md
                icon: rex-icon fa-info-circle
                itemClass: pull-right

default_config:
    api: 'hcti'
    hcti_username: ''
    hcti_api_key: ''
    h2in_api_key: ''
    fragment: 'thumb/html.php'
    media_manager_type: 'thumb'
    background_image: 'thumb_bg.png'
